title: "**Dr. Sidian Chen**"
author: "Sidian Chen"
description: "Welcome to Sidian's research webpage!"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true  # show site description and social links in the footer
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu
navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "cv.md", title: "CV"}
  - {file: "research.md", title: "Research"}
  - {file: "pub.md", title: "Publications"}
  - {file: "news.md", title: "News"} 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:sidianchen@email.arizona"}
  - {title: Google, icon: google, url: "https://scholar.google.com/citations?user=G6Aqt38AAAAJ&hl=en"}
  - {title: Subscribe, icon: rss, url: "https://www.researchgate.net/profile/Sidian-Chen"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/sidian-chen-4477609b"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/Sidian_Chen"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
